### ISSUE TITLE
GCC-8 produces broken executable

### ISSUE THREAD

**Issue by RossosHEX** [spoutn1k/mcmap#51] opened 2020-09-09 17:39 UTC
Greetings!

compiling seems to be ok
using Ubuntu 16.04 and gcc-8

trying to run ./mcmap -h gives Segmentation Fault

`:~/applications/minecraftmap/mcmap$ make realClean && make`
find src -name *o -exec rm {} \;
make -C scripts clean
make[1]: Entering directory '/home/-redacted-/applications/minecraftmap/mcmap/scripts'
find . -name '*o' -exec rm -fr {} \;
make[1]: Leaving directory '/home/-redacted-/applications/minecraftmap/mcmap/scripts'
rm -fr mcmap output.png src/colors.bson
make -C scripts realClean
make[1]: Entering directory '/home/-redacted-/applications/minecraftmap/mcmap/scripts'
find . -name '*o' -exec rm -fr {} \;
git clean -fdx
Removing json2bson
make[1]: Leaving directory '/home/-redacted-/applications/minecraftmap/mcmap/scripts'
make -C scripts json2bson
g++ -O3 -c -std=c++17 -Wall -I../src/include json2bson.cpp -o json2bson.default.o
g++ -O3 -c -std=c++17 -Wall -I../src/include ../src/include/fmt/format.cpp -o ../src/include/fmt/format.default.o
g++ json2bson.default.o ../src/include/fmt/format.default.o -s -lstdc++fs -o json2bson
./scripts/json2bson src/colors.json > src/colors.bson
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -fopenmp src/colors.cpp -o src/colors.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -fopenmp src/canvas.cpp -o src/canvas.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -fopenmp src/settings.cpp -o src/settings.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -fopenmp src/helper.cpp -o src/helper.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -fopenmp src/worldloader.cpp -o src/worldloader.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -fopenmp src/logger.cpp -o src/logger.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -fopenmp src/main.cpp -o src/main.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -fopenmp src/draw_png.cpp -o src/draw_png.default.o
make[1]: 'src/include/fmt/format.default.o' is up to date.
g++ src/colors.default.o src/canvas.default.o src/settings.default.o src/helper.default.o src/worldloader.default.o src/logger.default.o src/main.default.o src/draw_png.default.o src/include/fmt/format.default.o -lz -lpng -lgomp -o mcmap

`:~/applications/minecraftmap/mcmap$ ls -l`
total 648
drwxrwxr-x 2 -redacted- -redacted-   4096 Sep  9 19:39 assets
drwxrwxr-x 3 -redacted- -redacted-   4096 Sep  9 19:39 contrib
-rw-rw-r-- 1 -redacted- -redacted-  35149 Sep  9 19:39 LICENSE
-rw-rw-r-- 1 -redacted- -redacted-   1557 Sep  9 20:09 Makefile
-rwxrwxr-x 1 -redacted- -redacted- 596584 Sep  9 19:41 mcmap
-rw-rw-r-- 1 -redacted- -redacted-   7954 Sep  9 19:39 README.md
drwxrwxr-x 2 -redacted- -redacted-   4096 Sep  9 19:41 scripts
drwxrwxr-x 3 -redacted- -redacted-   4096 Sep  9 19:41 src

`~/applications/minecraftmap/mcmap$ ./mcmap -v`
`Segmentation fault (core dumped)`

`:~/applications/minecraftmap/mcmap$ gcc -v`
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.4.0-1ubuntu1\~16.04.1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.4.0 (Ubuntu 8.4.0-1ubuntu1~16.04.1) 

`:~/applications/minecraftmap/mcmap$ uname -v`
`#118~16.04.1-Ubuntu SMP Sat Sep 5 23:35:06 UTC 2020
`

`apt install libpng-dev`
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libpng12-dev' instead of 'libpng-dev'
libpng12-dev is already the newest version (1.2.54-1ubuntu1.1).

**Comment by spoutn1k** [comment] 2020-09-09 18:07
Hi ! Thanks for the detailed report.

First things first, the error log shows you using the `-v` instead of the `-h` option. I'm sure this is a typo and the `-h` option does not work either.

This obviously is something I cannot reproduce on my machine. My first thought would be an OpenMP error. Try compiling using `OPENMP=NO make -j` after having cleaned using `make realClean`. You will lose the ability to run parallel code but it will decomplexify the code a great deal.

**Comment by RossosHEX** [comment] 2020-09-09 18:17
Thank you for your prompt reply.

Following your suggestions I run the following:


`:~/applications/minecraftmap/mcmap$ make realClean`
find src -name *o -exec rm {} \;
make -C scripts clean
make[1]: Entering directory '/home/-redacted-/applications/minecraftmap/mcmap/scripts'
find . -name '*o' -exec rm -fr {} \;
make[1]: Leaving directory '/home/-redacted-/applications/minecraftmap/mcmap/scripts'
rm -fr mcmap output.png src/colors.bson
make -C scripts realClean
make[1]: Entering directory '/home/-redacted-/applications/minecraftmap/mcmap/scripts'
find . -name '*o' -exec rm -fr {} \;
git clean -fdx
make[1]: Leaving directory '/home/-redacted-/applications/minecraftmap/mcmap/scripts'


`:~/applications/minecraftmap/mcmap$ ls -l`
total 64
drwxrwxr-x 2 -redacted- -redacted-  4096 Sep  9 19:39 assets
drwxrwxr-x 3 -redacted- -redacted-  4096 Sep  9 19:39 contrib
-rw-rw-r-- 1 -redacted- -redacted- 35149 Sep  9 19:39 LICENSE
-rw-rw-r-- 1 -redacted- -redacted-  1557 Sep  9 19:39 Makefile
-rw-rw-r-- 1 -redacted- -redacted-  7954 Sep  9 19:39 README.md
drwxrwxr-x 2 -redacted- -redacted-  4096 Sep  9 21:10 scripts
drwxrwxr-x 3 -redacted- -redacted-  4096 Sep  9 21:10 src

`:~/applications/minecraftmap/mcmap$ OPENMP=NO make -j`
make -C scripts json2bson
g++ -O3 -c -std=c++17 -Wall -I../src/include json2bson.cpp -o json2bson.default.o
g++ -O3 -c -std=c++17 -Wall -I../src/include ../src/include/fmt/format.cpp -o ../src/include/fmt/format.default.o
g++ json2bson.default.o ../src/include/fmt/format.default.o -s -lstdc++fs -o json2bson
./scripts/json2bson src/colors.json > src/colors.bson
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -DDISABLE_OMP src/colors.cpp -o src/colors.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -DDISABLE_OMP src/canvas.cpp -o src/canvas.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -DDISABLE_OMP src/settings.cpp -o src/settings.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -DDISABLE_OMP src/helper.cpp -o src/helper.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -DDISABLE_OMP src/worldloader.cpp -o src/worldloader.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -DDISABLE_OMP src/logger.cpp -o src/logger.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -DDISABLE_OMP src/main.cpp -o src/main.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -DDISABLE_OMP src/draw_png.cpp -o src/draw_png.default.o
make[1]: 'src/include/fmt/format.default.o' is up to date.
g++ src/colors.default.o src/canvas.default.o src/settings.default.o src/helper.default.o src/worldloader.default.o src/logger.default.o src/main.default.o src/draw_png.default.o src/include/fmt/format.default.o -lz -lpng -o mcmap

`:~/applications/minecraftmap/mcmap$ ls -l`
total 644
drwxrwxr-x 2 -redacted- -redacted-   4096 Sep  9 19:39 assets
drwxrwxr-x 3 -redacted- -redacted-   4096 Sep  9 19:39 contrib
-rw-rw-r-- 1 -redacted- -redacted-  35149 Sep  9 19:39 LICENSE
-rw-rw-r-- 1 -redacted- -redacted-   1557 Sep  9 19:39 Makefile
-rwxrwxr-x 1 -redacted- -redacted- 591256 Sep  9 21:12 mcmap
-rw-rw-r-- 1 -redacted- -redacted-   7954 Sep  9 19:39 README.md
drwxrwxr-x 2 -redacted- -redacted-   4096 Sep  9 21:11 scripts
drwxrwxr-x 3 -redacted- -redacted-   4096 Sep  9 21:12 src

`:~/applications/minecraftmap/mcmap$ ./mcmap -h`
Segmentation fault (core dumped)

Is there an error log that I could attach somewhere?

**Comment by RossosHEX** [comment] 2020-09-09 18:36
I've tried gcc-9 and it now gives mcmap -h
It looks like I am unable to obtain gcc-10 under Ubuntu 16.04 though.

`:~/applications/minecraftmap/mcmap$ make realClean`
find src -name *o -exec rm {} \;
make -C scripts clean
make[1]: Entering directory '/home/-redacted-/applications/minecraftmap/mcmap/scripts'
find . -name '*o' -exec rm -fr {} \;
make[1]: Leaving directory '/home/-redacted-/applications/minecraftmap/mcmap/scripts'
rm -fr mcmap output.png src/colors.bson
make -C scripts realClean
make[1]: Entering directory '/home/-redacted-/applications/minecraftmap/mcmap/scripts'
find . -name '*o' -exec rm -fr {} \;
git clean -fdx
make[1]: Leaving directory '/home/-redacted-/applications/minecraftmap/mcmap/scripts'

`:~/applications/minecraftmap/mcmap$ make -j`
make -C scripts json2bson
g++ -O3 -c -std=c++17 -Wall -I../src/include json2bson.cpp -o json2bson.default.o
g++ -O3 -c -std=c++17 -Wall -I../src/include ../src/include/fmt/format.cpp -o ../src/include/fmt/format.default.o
g++ json2bson.default.o ../src/include/fmt/format.default.o -s -lstdc++fs -o json2bson
./scripts/json2bson src/colors.json > src/colors.bson
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -fopenmp src/colors.cpp -o src/colors.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -fopenmp src/canvas.cpp -o src/canvas.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -fopenmp src/settings.cpp -o src/settings.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -fopenmp src/helper.cpp -o src/helper.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -fopenmp src/worldloader.cpp -o src/worldloader.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -fopenmp src/logger.cpp -o src/logger.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -fopenmp src/main.cpp -o src/main.default.o
g++ -O3 -std=c++17 -c -Wall -fomit-frame-pointer -pedantic -D_FILE_OFFSET_BITS=64 -Isrc/include -fopenmp src/draw_png.cpp -o src/draw_png.default.o
make[1]: 'src/include/fmt/format.default.o' is up to date.
g++ src/colors.default.o src/canvas.default.o src/settings.default.o src/helper.default.o src/worldloader.default.o src/logger.default.o src/main.default.o src/draw_png.default.o src/include/fmt/format.default.o -lz -lpng -lgomp -o mcmap

`:~/applications/minecraftmap/mcmap$ ls -l`
total 736
drwxrwxr-x 2 -redacted- -redacted-   4096 Sep  9 19:39 assets
drwxrwxr-x 3 -redacted- -redacted-   4096 Sep  9 19:39 contrib
-rw-rw-r-- 1 -redacted- -redacted-  35149 Sep  9 19:39 LICENSE
-rw-rw-r-- 1 -redacted- -redacted-   1557 Sep  9 19:39 Makefile
-rwxrwxr-x 1 -redacted- -redacted- 686336 Sep  9 21:25 mcmap
-rw-rw-r-- 1 -redacted- -redacted-   7954 Sep  9 19:39 README.md
drwxrwxr-x 2 -redacted- -redacted-   4096 Sep  9 21:24 scripts
drwxrwxr-x 3 -redacted- -redacted-   4096 Sep  9 21:25 src

`:~/applications/minecraftmap/mcmap$ gcc -v`
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-10ubuntu2\~16.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2~16.04) 

`:~/applications/minecraftmap/mcmap$ ./mcmap -h`
Usage: ./mcmap <options> WORLDPATH

  -from X Z           coordinates of the block to start rendering at
  -to X Z             coordinates of the block to stop rendering at
  -min/max VAL        minimum/maximum Y index of blocks to render
  -file NAME          output file; default is 'output.png'
  -colors NAME        color file to use; default is 'colors.json'
  -nw -ne -se -sw     the orientation of the map
  -nether             render the nether
  -end                render the end
  -dim[ension] NAME   render a dimension by namespaced ID
  -nowater            do not render water
  -nobeacons          do not render beacon beams
  -shading            toggle shading (brightens blocks depending on height)
  -splits VAL         render with VAL threads
  -marker X Z color   draw a marker at X Z of the desired color
  -padding VAL        padding to use around the image (default 5)
  -h[elp]             display an option summary
  -v[erbose]          toggle debug mode
  -dumpcolors         dump a json with all defined colors


I notice a significant size increase in the mcmap executable, from 591256 to 686336.
It also took longer to compile. Could it be skipping some files while compiling under gcc-8?

Gonna try and render a small map now.


`:~/applications/minecraftmap/mcmap$ ./mcmap -from 48 223 -to 207 64 -v $HOME/.minecraft/saves/testworld/`
[Debug] World spans from -6128.-38160 to 19823.15375
[Error] Nothing to render: -from X Z has to be <= -to X Z
Usage: ./mcmap <options> WORLDPATH

  -from X Z           coordinates of the block to start rendering at
  -to X Z             coordinates of the block to stop rendering at
  -min/max VAL        minimum/maximum Y index of blocks to render
  -file NAME          output file; default is 'output.png'
  -colors NAME        color file to use; default is 'colors.json'
  -nw -ne -se -sw     the orientation of the map
  -nether             render the nether
  -end                render the end
  -dim[ension] NAME   render a dimension by namespaced ID
  -nowater            do not render water
  -nobeacons          do not render beacon beams
  -shading            toggle shading (brightens blocks depending on height)
  -splits VAL         render with VAL threads
  -marker X Z color   draw a marker at X Z of the desired color
  -padding VAL        padding to use around the image (default 5)
  -h[elp]             display an option summary
  -v[erbose]          toggle debug mode
  -dumpcolors         dump a json with all defined colors

`:~/applications/minecraftmap/mcmap$ ./mcmap -from 48 64 -to 207 223 -v $HOME/.minecraft/saves/testworld/`
[Debug] World spans from -6128.-38160 to 19823.15375
mcmap 3.0.0 64bit (compatible with Minecraft v1.13+)
[Debug] Loaded 253 colors out of the 760 declared
[Debug] Image dimensions are 650x781, 32bpp, 0.48413277MiB
Writing to file...
Job complete.

Image got produced.

![output](https://user-images.githubusercontent.com/8318353/92639343-52923400-f2e4-11ea-9fd6-67d1a70917a4.png)

Cheers!

**Comment by spoutn1k** [comment] 2020-09-09 19:24
Splendid ! Interesting how gcc 8 made a broken executable. I'll take a look once I have some time.

**Comment by spoutn1k** [comment] 2020-09-10 00:47
Replicated in a container. This exact error was fixed some time ago but the fix got disabled when updating the Makefile. The latest commit should enable `gcc-8` to work and create a functionnal `mcmap`.

It also takes a lot less time to compile. `g++-9` took twice the amount of time to compile for similar performance. Weird.
Please test on your side if desired, or I'll close the issue in two weeks.

**Closed as completed** 2020-09-25 16:54 UTC
Labels: Compilation error, User feedback needed
